name: lightnav-habitat
channels:
  - aihabitat
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - habitat-sim=0.3.1=py3.9_headless_bullet_linux_3d6d67d6deae4ab2472cc84df7a3cef1503f606d
  - numpy=1.23.5
  - quaternion
  - attrs
  - pillow
  - scipy
  - numba
  - imageio
  - tqdm
  - gitpython
  - pip
  - libopengl
  - libegl
  - libgl
  - libglx
